### ISSUE TITLE
`yarn pack:webhosting` expects a file called `log.toml` to exist.

### ISSUE THREAD

**Issue by Charles-Johnson** [maidsafe/safe_examples#394]
After running `yarn install-all` in the `safe_examples` directory I ran `yarn pack:webhosting` which raised this error:

>$ node ../post-packaging.js -e web_hosting_manager
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

>Error: ENOENT: no such file or directory, stat '~/safe_examples/log.toml'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (~/safe_examples/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (~/safe_examples/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at Object.<anonymous> (~/safe_examples/post-packaging.js:83:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bochaco** [comment]
Hi @Charles-Johnson , we just migrated this project onto its own repository, can you please clone this other repo instead and try to build it from there? https://github.com/maidsafe/safe-web-hosting-manager-electron
If you encounter any issue, please report it in that repository.
