### ISSUE TITLE
Problems setting up to build dns_example

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_examples#7]
I'm new to almost all of this so blindly following instructions and winging it. I'm on Debian Jesse x64.

I have built the libsafe_ffi.so (ignoring the bit about libsodium which I think is now static, but which I might have anyway) and copied to safe_api and an adding the other bits to build dns_example.

I had some warnings about versions when doing...
```npm install```
\# Three warnings:
```
npm WARN engine electron-debug@0.1.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})

npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
```
...
Nice big install of the electron stuff

Had to install bower and then install it for dns_example ("a package manager for the web" - https://github.com/bower/bower)
```sudo npm install -g bower```
\# Three warniings:
```
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
```

I'm not sure if any of the above is a problem as I've not been using npm long and always seem to get warnings from it, and not knowing what they mean have proceeded without issue.

Following the dns_example/README.md I get to 
```
./node_modules/.bin/electron-rebuild
```
which does nothing for a while and then spews a lot of make output about visiting directories and so on, which all look good until shortly after this (see "Unsupported target version: 0.30.4" below).

Any clues here? I seem to be stuck and not knowing anything about electron or npm I think it'll take me too long to sort this out without help. Any help appreciated. **My aim is to get to the point where I can see what the app is doing in relation to SAFE API and so start to understand more about the DNS and Structured Data.** I was hoping getting this building and then starting to inspect your code would help.
```
Downloading electron-v0.30.4-linux-x64.zip
[============================================>] 100.0% of 35.99 MB (827.31 kB/s)

> nslog@2.0.0 install /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

make: Entering directory '/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_linux.o
  SOLINK_MODULE(target) Release/obj.target/nslog.node
  COPY Release/nslog.node
make: Leaving directory '/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog/build'

> spawn-sync@1.0.13 postinstall /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync
> node postinstall


> thread-sleep@1.0.4 install /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.30.4

../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
In file included from ../src/ffi.cc:3:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/deps/v8/include/v8.h:19:0,
                 from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/src/node.h:42,
                 from ../src/ffi.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
../src/ffi.cc: In static member function ‘static void FFI::FinishAsyncFFICall(uv_work_t*)’:
../src/ffi.cc:387:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/src/node.h:295): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     FatalException(try_catch);
                             ^
In file included from ../src/callback_info.cc:8:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/deps/v8/include/v8.h:19:0,
                 from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/src/node.h:42,
                 from ../src/callback_info.cc:5:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
In file included from ../src/callback_info.cc:8:0:
../src/callback_info.cc: In static member function ‘static void CallbackInfo::Callback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/ffi.h:25:72: warning: ‘void NanThrowError(const char*, int)’ is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
 #define THROW_ERROR_EXCEPTION_WITH_STATUS_CODE(x, y) NanThrowError(x, y)
                                                                        ^
../src/callback_info.cc:151:12: note: in expansion of macro ‘THROW_ERROR_EXCEPTION_WITH_STATUS_CODE’
     return THROW_ERROR_EXCEPTION_WITH_STATUS_CODE("ffi_prep_closure() Returned Error", status);
            ^
In file included from ../src/threaded_callback_invokation.cc:2:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/deps/v8/include/v8.h:19:0,
                 from /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.4/src/node.h:42,
                 from ../src/threaded_callback_invokation.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.4
node-pre-gyp ERR! stack     at get_runtime_abi (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "node" "/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep
node-pre-gyp ERR! node -v v0.10.29
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.30.4" "--arch=x64"
npm ERR! node v0.10.29
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mrh/src/safe_examples/dns_example/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/home/mrh/src/safe_examples/dns_example/node_modules/electron-rebuild/lib/spawn.js:53:26)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by theWebalyst** [comment]
For fun I tried "npm start" anyway. I get a funtional dns_example and got to the point of publishing a template website, which then did not complete the upload. I looks like it fails to load the libsafe_ffi.so. Might that be because I didn't do what I was told regarding libsodium - is that still needed as stated in the safe_ffi/README.md? I'll ask in an issue over there...

Anyway, this is the console output I got here:

```
 npm start

> safe_dns_example@0.0.1 start /home/mrh/src/safe_examples/dns_example
> electron .

[10030:0927/214102:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
/home/mrh/src/safe_examples/dns_example
[10056:0927/214102:INFO:renderer_main.cc(200)] Renderer process started
[10030:0927/214153:INFO:CONSOLE(38)] "Creating directory safe_uploader_template115827-10056-1gkxunl", source: /home/mrh/src/safe_examples/dns_example/src/scripts/uploader.js (38)
[10030:0927/214153:INFO:CONSOLE(41)] "Load failed : ./src/scripts/safe_api/", source: /home/mrh/src/safe_examples/dns_example/src/scripts/safe_api/api.js (41)
[10030:0927/214153:INFO:CONSOLE(35)] "Child Process Aborted", source: /home/mrh/src/safe_examples/dns_example/src/scripts/safe_api/api.js (35)
```

**Comment by theWebalyst** [comment]
UPDATE: I've installed the latest node & npm from http://nodejs.org to try and clean up the version warnings but I'm now getting less far than I did with the old debian packaged distributions.

Now, when I try to "npm install" it falls over much earlier, during rebuild of node-gyp trying to make ffi.o. What Linux distro and node/npm versions are you using?

I currently have:
```
$ node -v
v4.1.2
$ npm -v
2.14.4
```

Here's the error output (debian jesse):
```
$ npm install
npm WARN package.json safe_dns_example@0.0.1 No license field.
 
> ffi@1.3.2 install /home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/ffi
> node-gyp rebuild

make: Entering directory '/home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:3:0:
../src/ffi.h:3:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS true
 ^
In file included from /home/mrh/.node-gyp/4.1.2/include/node/v8.h:19:0,
                 from /home/mrh/.node-gyp/4.1.2/include/node/node.h:42,
                 from ../src/ffi.cc:1:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 ^
In file included from ../src/ffi.h:18:0,
                 from ../src/ffi.cc:3:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../src/ffi.cc:2:0:
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/ffi.h:18:0,
                 from ../src/ffi.cc:3:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/ffi.cc: In function ‘v8::Handle<v8::Value> WrapPointer(char*, size_t)’:
../src/ffi.cc:25:63: error: no matching function for call to ‘NanNewBufferHandle(char*&, size_t&, void (&)(char*, void*), void*&)’
     NanNewBufferHandle(ptr, length, wrap_pointer_cb, user_data)
                                                               ^
../node_modules/nan/nan.h:483:68: note: in definition of macro ‘NanEscapeScope’
 # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                                                                    ^
../src/ffi.cc:25:63: note: candidates are:
     NanNewBufferHandle(ptr, length, wrap_pointer_cb, user_data)
                                                               ^
../node_modules/nan/nan.h:483:68: note: in definition of macro ‘NanEscapeScope’
 # define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                                                                    ^
../node_modules/nan/nan.h:754:36: note: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:754:36: note:   candidate expects 3 arguments, 4 provided
../node_modules/nan/nan.h:764:36: note: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:764:36: note:   candidate expects 2 arguments, 4 provided
../node_modules/nan/nan.h:771:36: note: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:771:36: note:   candidate expects 1 argument, 4 provided
../src/ffi.cc: In static member function ‘static void FFI::FinishAsyncFFICall(uv_work_t*)’:
../src/ffi.cc:387:29: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/mrh/.node-gyp/4.1.2/include/node/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     FatalException(try_catch);
                             ^
../src/ffi.cc: In function ‘v8::Handle<v8::Value> WrapPointer(char*, size_t)’:
../src/ffi.cc:27:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ffi_bindings.target.mk:99: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/ffi
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
> nslog@2.0.0 install /home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

make: Entering directory '/home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
In file included from ../src/main.cc:3:0:
../node_modules/nan/nan.h:260:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:255:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:660:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:660:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:664:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:664:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:671:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:671:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/main.cc:3:
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mrh/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/main.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:675:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
nslog.target.mk:91: recipe for target 'Release/obj.target/nslog/src/main.o' failed
make: *** [Release/obj.target/nslog/src/main.o] Error 1
make: Leaving directory '/home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mrh/src/maidsafe-rust/safe_examples/dns_example/node_modules/electron-rebuild/node_modules/nslog
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@1.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mrh/src/maidsafe-rust/safe_examples/dns_example/npm-debug.log
```

**Comment by krishnaIndia** [comment]
FFI bindings are not needed anymore with the launcher integration
